[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2024"


[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.13.0"
intervallum = "1.4.1"
gcollections = "1.5.0"
regex = "1.11.1"
scan_fmt = "0.2.6"
